### ISSUE TITLE
Issue with background-image css property?

### ISSUE THREAD

**Issue by brpsmith** [Deschtex/html2react#19]
Hello - Thank you for creating this solution.  It is very helpful.  One thing I noticed is that the URL for the background-image property does not properly convert.  For example the following HTML:

`<td style="background-position:center; background-position:top; background-image: url('https://s3.amazonaws.com/preferably-dev/templates/images/bg_desktop.png');">
`
converts to:

`<td style="background-position:center; background-position:top; background-image: url('https');">`

Do you know if this is expected/part of react validation or some other dependency?

Thanks.

Brian

**Comment by Deschtex** [comment]
Hey @brpsmith, I'm glad that you find it helpful!

The issue described is caused by a naive `split` when separating the key from the value in e.g. `background-image: url(https://...)`.

The fix will be based on **v1.0.0**, which I released earlier today. It (unfortunately) expects `react@^15.4.0` and `react-dom@^15.4.0` as peer dependencies.

If that's a problem for you I'll need to add the fix on top of **v0.3.5** as well.

Thanks for reporting it! I'll notify you when it's fixed.

**Comment by Deschtex** [comment]
@brpsmith I just published **v1.0.1**. Could you please verify it fixes the issue?

**Comment by brpsmith** [comment]
Thanks @Deschtex!  It works perfectly.  Sincerely appreciate it.
