### ISSUE TITLE
Ignore text nodes that only contain whitespace (spaces, newlines)

### ISSUE THREAD

**Issue by Deschtex** [Deschtex/html2react#7]

**Comment by Deschtex** [comment]
Fixed by #8

**Comment by pavelvolek** [comment]
Why are the white spaces ignored?

With

`<p>Writing <del>some</del> <b>HTML with</b> <a href=\"https://github.com\" target=\"_blank\">link</a>`

I have

Writing <del>some</del><b>HTML with</b>[link](https://github.com)

instead of

Writing <del>some</del> <b>HTML with</b> [link](https://github.com)
